service: IexBee

plugins:
  - serverless-layers

provider:
  name: aws
  runtime: python3.8
  stage: dev
  role: arn:aws:iam::449798490924:role/DynamoRoleForLambda
  deploymentBucket:
    name: iexbee-serverless-deployment-${opt:stage, self:provider.stage}

functions:
  market-snap:
    handler: handler.lambda_handler
    environment:
      API_TOKEN: ${self:custom.config.env_vars.API_TOKEN, self:custom.default_config.env_vars.API_TOKEN}
      JSON_LOGS: ${self:custom.config.env_vars.JSON_LOGS, self:custom.default_config.env_vars.JSON_LOGS}
      TEST_ENVIRONMENT: ${self:custom.config.env_vars.TEST_ENVIRONMENT, self:custom.default_config.env_vars.TEST_ENVIRONMENT}
      TEST_STOCKS: ${self:custom.config.env_vars.TEST_STOCKS, self:custom.default_config.env_vars.TEST_STOCKS}

package:
  exclude:
    - node_modules/**
    - config/**
    - venv_linux/**
    - .vscode/**
    - .github/**
    - package-lock.json
    - local.env

custom:
  default_config: ${file(config/common.yml)}
  config: ${file(config/${opt:stage, self:provider.stage}.yml)}
  serverless-layers:
    compatibleRuntimes: 
      - python3.8

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: IexSnapshot-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
          - AttributeName: symbol
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: symbol
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: Reverse_index
            KeySchema:
              - AttributeName: symbol
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${self:custom.config.dynamodb.index_rcu, self:custom.default_config.dynamodb.index_rcu}
              WriteCapacityUnits: ${self:custom.config.dynamodb.index_wcu, self:custom.default_config.dynamodb.index_wcu}
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.config.dynamodb.rcu, self:custom.default_config.dynamodb.rcu}
          WriteCapacityUnits: ${self:custom.config.dynamodb.wcu, self:custom.default_config.dynamodb.wcu}
