name: integration_tests

on:
  release:
    types: [published]

jobs:
  integration:
    runs-on: ubuntu-latest
    container:
      image: nikolaik/python-nodejs:python3.8-nodejs14-alpine
    env:
      TEST_ENVIRONMENT: 'True'
      TEST_STOCKS: 'True'
      TABLE: 'TestIexSnapshot'
      LAMBDA_NAME: 'TestLambda' 
      API_TOKEN: ${{ secrets.API_TOKEN_TEST }} 
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup
        run: |
          pip install -r requirements.txt
          pip install awscli
          npm install -g serverless
          sls plugin install --name serverless-layers
      - name: tests
        run: |
          python handler.py
          aws dynamodb delete-table \
            --table-name $TABLE
      - name: sls deploy
        run: |
          sls deploy --region $AWS_DEFAULT_REGION --stage prod
        