name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-alpine
    services:
      localstack:
        image: localstack/localstack:0.10.7
        ports:
          - 4569:4569
        env:
          SERVICES: dynamodb
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: tests
        run: python -m pytest -s -v tests
        env: 
          DYNAMO_URI: http://localstack:4569
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: foo
          AWS_SECRET_ACCESS_KEY: bar